# ----------------------------- #
theme: jekyll-theme-minimal
title: My ZKP and Web3 Blog
description: A journey into Zero-Knowledge Proofs, blockchain, and decentralized finance.
author: Sean Kane
email: kanesean391024@gmail.remote_theme: pages-themes/minimal@v0.2.0


