# ----------------------------- #
# 1. Basic Site Settings
# ----------------------------- #
title: My ZKP and Web3 Blog
description: A journey into Zero-Knowledge Proofs, blockchain, and decentralized finance.
author: Sean Kane
email: kanesean391024@gmail.com


